//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaraokePlayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaraokePlayer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karaoke Player.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ArtistLabel {
            get {
                return ResourceManager.GetString("ArtistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string AudioLabel {
            get {
                return ResourceManager.GetString("AudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        public static string BpmLabel {
            get {
                return ResourceManager.GetString("BpmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string CoverLabel {
            get {
                return ResourceManager.GetString("CoverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cover.
        /// </summary>
        public static string CoverPlaceholder {
            get {
                return ResourceManager.GetString("CoverPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen Mode.
        /// </summary>
        public static string EnterFullscreenButton {
            get {
                return ResourceManager.GetString("EnterFullscreenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed Mode.
        /// </summary>
        public static string EnterWindowedButton {
            get {
                return ResourceManager.GetString("EnterWindowedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics Overlay.
        /// </summary>
        public static string LyricsOverlayPlaceholder {
            get {
                return ResourceManager.GetString("LyricsOverlayPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsButton {
            get {
                return ResourceManager.GetString("OptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Library.
        /// </summary>
        public static string ReloadLibraryButton {
            get {
                return ResourceManager.GetString("ReloadLibraryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining:.
        /// </summary>
        public static string RemainingLabel {
            get {
                return ResourceManager.GetString("RemainingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Song.
        /// </summary>
        public static string SelectedSongTitleLabel {
            get {
                return ResourceManager.GetString("SelectedSongTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip To First Note.
        /// </summary>
        public static string SkipToFirstNoteButton {
            get {
                return ResourceManager.GetString("SkipToFirstNoteButton", resourceCulture);
            }
        }

        public static string SkipToFirstNotePrompt {
            get {
                return ResourceManager.GetString("SkipToFirstNotePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Library.
        /// </summary>
        public static string SongLibraryTitle {
            get {
                return ResourceManager.GetString("SongLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select songs folder.
        /// </summary>
        public static string SongsFolderDialogTitle {
            get {
                return ResourceManager.GetString("SongsFolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs folder.
        /// </summary>
        public static string SongsFolderLabel {
            get {
                return ResourceManager.GetString("SongsFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Player.
        /// </summary>
        public static string StartQueueButton {
            get {
                return ResourceManager.GetString("StartQueueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs loaded..
        /// </summary>
        public static string StatusLoaded {
            get {
                return ResourceManager.GetString("StatusLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading songs....
        /// </summary>
        public static string StatusLoading {
            get {
                return ResourceManager.GetString("StatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs folder not found..
        /// </summary>
        public static string StatusMissing {
            get {
                return ResourceManager.GetString("StatusMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string VideoLabel {
            get {
                return ResourceManager.GetString("VideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Surface.
        /// </summary>
        public static string VideoSurfacePlaceholder {
            get {
                return ResourceManager.GetString("VideoSurfacePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless fullscreen.
        /// </summary>
        public static string WindowModeBorderless {
            get {
                return ResourceManager.GetString("WindowModeBorderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window mode.
        /// </summary>
        public static string WindowModeLabel {
            get {
                return ResourceManager.GetString("WindowModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string WindowModeWindowed {
            get {
                return ResourceManager.GetString("WindowModeWindowed", resourceCulture);
            }
        }
    }
}
